### ISSUE TITLE
Lazy Loading with blocks of size 1

### ISSUE THREAD

**Issue by danifm1321** [Asperi-Demo/4SwiftUI#3]
First of all, I wanted to thank you for the [code for the lazy loading of a list](https://github.com/Asperi-Demo/4SwiftUI/blob/master/Answers/Lazy_loading_on_List.md). 

I'm trying to use it in a ForEach that works with a heavy view (a lot of UIViewRepresentables of UITextViews and UIScrollViews) so I set the block size 1. Now it only loads the first view.

**Comment by Asperi-Demo** [comment]
Fixed. Try updated variant.

**Comment by danifm1321** [comment]
It works! Thank you so much.
